openapi: 3.0.3
info:
  title: "UECS Navi API"
  version: "1.0.0"
paths:
  /climate-datas:
    get:
      operationId: getClimateData
      tags:
        - private
      summary: Get climate data list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClimateDatasResponse"
  /houses:
    get:
      operationId: getHouses
      tags:
        - private
      summary: Get houses list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HousesResponse"
    post:
      operationId: createHouse
      tags:
        - private
      summary: Create a house
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HousesRequest"
      responses:
        "200":
          description: OK

  /houses/{house-id}:
    parameters:
      - $ref: "#/components/parameters/house-id"
    get:
      operationId: getDevice
      tags:
        - private
      summary: Get devices list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeviceResponse"
  /houses/{house-id}/devices:
    parameters:
      - $ref: "#/components/parameters/house-id"
    post:
      operationId: createDevice
      tags:
        - private
      summary: Create device
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRequest"
      responses:
        "200":
          description: OK
  /houses/{house-id}/m304/{m304-id}/controls:
    parameters:
      - $ref: "#/components/parameters/house-id"
      - $ref: "#/components/parameters/m304-id"
    get:
      operationId: getM304
      tags: 
        - private
      summary: Get M304 control information
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/M304ControlResponse"

components:
  parameters:
    house-id:
      name: house-id
      in: path
      required: true
      schema:
        type: integer
    m304-id:
      name: m304-id
      in: path
      required: true
      schema:
        type: integer

  schemas:
    DeviceControl:
      type: object
      properties:
        id: 
          type: integer
        name:
          type: string

    HousesRequest:
      type: string
    DeviceRequest:
      type: object
      properties:
        device_name:
          type: string
        climate_data_id:
          type: integer
        unit:
          type: string
        set_point:
          type: number
          format: double
        duration:
          type: integer
          nullable: true

    ClimateDatasResponse:
      type: object
      properties:
        id:
          type: integer
        climate_data:
          type: string
        unit:
          type: string
    HousesResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    DeviceResponse:
      type: object
      properties:
        id:
          type: integer
        device_name:
          type: string
        climate_data:
          type: string
        unit:
          type: string
        set_point:
          type: number
          format: double
        duration:
          type: integer
    M304ControlResponse:
      type: object
      properties:
        id: 
          type: integer
        start_time:
          type: string
          pattern: "^([01]?[0-9]|2[0-3]):[0-5][0-9]?$"
          description: "開始時刻（HH:mmまたはHH:mm:ss形式）"
        end_time:
          type: string
          pattern: "^([01]?[0-9]|2[0-3]):[0-5][0-9]?$"
          description: "終了時刻（HH:mmまたはHH:mm:ss形式）"
        device_controls:
          type: array
          items:
            $ref: "#/components/schemas/DeviceControl"
        
