version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
