CREATE TABLE comparison_operators (
    id INT AUTO_INCREMENT PRIMARY KEY,
    comparison_operator VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
