CREATE TABLE workflows (
    id INT AUTO_INCREMENT PRIMARY KEY,
    m304_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (m304_id) REFERENCES m304s(id) ON DELETE RESTRICT
);
