// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mysqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ClimateData struct {
	ID   int32
	Name string
	Unit string
}

type ComparisonOperator struct {
	ID                 int32
	ComparisonOperator string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Condition struct {
	ID                   int32
	ClimateDataID        int32
	TimeScheduleRowID    int32
	ComparisonOperatorID int32
	SetPoint             float64
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Device struct {
	ID            int32
	ClimateDataID int32
	M304ID        int32
	Name          string
	Rly           sql.NullInt32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Edge struct {
	ID           int32
	WorkflowID   int32
	SourceNodeID string
	TargetNodeID string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type House struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type M304 struct {
	ID         int32
	HouseID    int32
	MacAddr    string
	DhcpFlg    bool
	IpAddr     sql.NullString
	NetMask    sql.NullString
	Defgw      sql.NullString
	Dns        sql.NullString
	VenderName string
	NodeName   sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Node struct {
	ID             int32
	WorkflowID     int32
	WorkflowNodeID string
	Type           string
	Data           json.RawMessage
	PositionX      float64
	PositionY      float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TimeSchedule struct {
	ID        int32
	M304ID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TimeScheduleRow struct {
	ID             int32
	TimeScheduleID int32
	StartTime      time.Time
	EndTime        time.Time
	WorkflowID     int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Workflow struct {
	ID        int32
	M304ID    int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WorkflowOperation struct {
	ID         int32
	WorkflowID int32
	Relay1     sql.NullBool
	Relay2     sql.NullBool
	Relay3     sql.NullBool
	Relay4     sql.NullBool
	Relay5     sql.NullBool
	Relay6     sql.NullBool
	Relay7     sql.NullBool
	Relay8     sql.NullBool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
