// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: time_schedules.sql

package mysqlc

import (
	"context"
)

const createTimeSchedule = `-- name: CreateTimeSchedule :execlastid
INSERT INTO time_schedules (m304_id)
VALUES (?)
`

func (q *Queries) CreateTimeSchedule(ctx context.Context, m304ID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTimeSchedule, m304ID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getTimeScheduleFromM304 = `-- name: GetTimeScheduleFromM304 :one
SELECT id, m304_id
FROM time_schedules
WHERE m304_id = ?
`

type GetTimeScheduleFromM304Row struct {
	ID     int32
	M304ID int32
}

func (q *Queries) GetTimeScheduleFromM304(ctx context.Context, m304ID int32) (GetTimeScheduleFromM304Row, error) {
	row := q.db.QueryRowContext(ctx, getTimeScheduleFromM304, m304ID)
	var i GetTimeScheduleFromM304Row
	err := row.Scan(&i.ID, &i.M304ID)
	return i, err
}
